# Required parameters
brightness_factor: 10.0  # Default value is 0 (brightness unchanged)
saturation_factor: 1.25  # Default value is 1 (saturation unchanged)

# Optional parameters
white_balance:
  enabled: True
  algorithm: grayworld  # Options: percentile, grayworld, lab
  percentile: 99.0  # *only used if white_balance_type is 'percentile'*

local_contrast_enhancement:
  enabled: True
  degree: 1.5
  smoothing: 0.2

lecarm_tonemapping:  # Global method
  enabled: False
  camera_model: sigmoid  # Options: sigmoid, gamma, betagamma, preferred
  downsampling: 1.0
  scaling: 1.2

spatial_tonemapping:  # Local method
  enabled: True
  smoothing: 0.2
  mid_tone: 0.5
  tonal_width: 0.5
  areas_dark: 0.5
  areas_bright: 0.5
  preserve_tones: True

denoising:
  enabled: False
  diameter: 5
  sigma_color: 50.0
  sigma_space: 50.0

clahe:
  enabled: False
  kernel_size: 5
  clip_limit: 2.0