# Required parameters
white_balance_type: gray_world # Options: percentile, gray_world

# Optional parameters with default values
brightness_factor: 10.0
saturation_factor: 1.25

# CLAHE parameters
skip_clahe: False
clahe_kernel_size: 5
clahe_clip_limit: 2.0

# White balance percentile parameter (only used if white_balance_type is 'percentile')
white_balance_percentile: 99

# Denoising parameters
skip_denoising: False
denoise_diameter: 5
denoise_sigma_color: 50.0
denoise_sigma_space: 50.0